DD-17: added restrict to image size and type
Adm1RalDen/online-draw-dashboard pull request #33
Opened 2022-10-06 12:12 UTC by YuraStork

2022-10-11 14:17 UTC, Adm1RalDen commented on src/utils/countBytes.ts
> +    case 'GB':
нащо тобі гігабайти на цьому сайті ?

2022-10-11 14:19 UTC, Adm1RalDen commented on src/utils/countBytes.ts
> +      return amount * 1024 * 1024
return amount * 1024 ** 2

2022-10-19 11:13 UTC, Andrew01011997 requested changes

2022-10-19 11:13 UTC, Andrew01011997 commented on src/components/fileInput/index.tsx
> +      <FileInputStyled {...others} type='file' ref={inputRef} onChange={handleChange} />
`input` inside `label` will call click from input when clicking on a `label`

2022-10-19 11:13 UTC, Andrew01011997 commented on src/components/image-crop/index.tsx
> +        toast.error('File is too big (should been less then 2Mb)')
save logic as in previous file. Move to utils or something like this

2022-10-19 11:13 UTC, Andrew01011997 commented on src/utils/portal.tsx
> +  z-index: 9998;
Why so big `z-index`?

2022-10-21 12:46 UTC, YuraStork commented on src/utils/countBytes.ts
> +    case 'GB':
Видалив ГігаБайти

2022-10-21 12:56 UTC, YuraStork commented on src/utils/countBytes.ts
> +      return amount * 1024 * 1024
Виправив

2022-10-24 07:40 UTC, YuraStork commented on src/components/fileInput/index.tsx
> +      <FileInputStyled {...others} type='file' ref={inputRef} onChange={handleChange} />
Виправив

2022-10-31 09:18 UTC, YuraStork commented on src/utils/portal.tsx
> +  z-index: 9998;
Was reduce zIndex values to 10

2022-10-31 09:19 UTC, YuraStork commented on src/components/image-crop/index.tsx
> +        toast.error('File is too big (should been less then 2Mb)')
Was created function wich will check file and return boolean result

2022-11-02 09:20 UTC, Adm1RalDen commented on src/components/fileInput/index.tsx
> +        <>
нащо ти обернув додатково фрагментом коли в цьому немає необхідності ?

2022-11-02 09:21 UTC, Adm1RalDen commented on src/components/fileInput/styles.tsx
> +}
що типізація робить у файлі зі стилями ? Воно одразово використовується на скільки я бачу, передай напряму типазацію до компоненти яку стилізуєш

2022-11-02 09:23 UTC, Adm1RalDen commented on src/components/fileInput/styles.tsx
> +const FileInputFileInfo = styled.div<Props>`
не зрозуміла назва, переглянь будь ласка якісь шаблони найменувань файлів, компонентів тощо

2022-11-02 09:24 UTC, Adm1RalDen commented on src/components/fileInput/styles.tsx
> +  padding: 10px 10px 0px 0px;
поясни ситуацію в якій тобі необхідно добавляти відступ лише зверху та справа ?

2022-11-02 09:25 UTC, Adm1RalDen commented on src/components/fileInput/types.ts
> +  }
ця типізація виглядає жахливо

2022-11-02 09:28 UTC, Adm1RalDen commented on src/utils/countBytes.ts
> +export const countBytes = (amount: number, type: 'MB' | 'KB') => {
'MB' | 'KB' - можна винести в enum

2022-11-02 09:29 UTC, Adm1RalDen commented on src/utils/countBytes.ts
> +export const countBytes = (amount: number, type: 'MB' | 'KB') => {
також замінити усі їх включення на використання цьго enum

2022-11-02 09:31 UTC, Adm1RalDen commented on src/utils/isValidFileSize.ts
> +  return true
функція має повернути лише  file.size > size, навіщо ти руками передаєш true / false ?

2022-11-02 11:31 UTC, YuraStork commented on src/components/fileInput/styles.tsx
> +  padding: 10px 10px 0px 0px;
Така ситуація є кнопка завантаження файлу, при натисканні якщо файл валідний, зпід кнопки виїде блок з назвою файлу та іконка хрестика для видалення файлу, тепер для того щоб текст був по центру і текст не заходив під іконку я використав padding

2022-11-02 11:40 UTC, YuraStork commented on src/components/fileInput/types.ts
> +  }
Ось так краще

```
export type FileInputProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> & {
  name: string
  onChange: FunctionWithParams<ChangeEvent<HTMLInputElement> | null>
  colorInfo?: 'black' | 'white'
}
```

2022-11-02 13:32 UTC, YuraStork commented on src/components/fileInput/styles.tsx
> +}
Незрозумів як можна передати на пряму, поки виніс в types.ts

2022-11-02 13:38 UTC, YuraStork commented on src/components/fileInput/index.tsx
> +        <>
Видалив обгортку

2022-11-02 13:38 UTC, YuraStork commented on src/components/fileInput/styles.tsx
> +const FileInputFileInfo = styled.div<Props>`
Виправив на FileInfoWrapper

2022-11-02 13:39 UTC, YuraStork commented on src/utils/isValidFileSize.ts
> +  return true
Виправив

2022-11-02 13:40 UTC, YuraStork commented on src/utils/isValidFileSize.ts
> +  return true
Там додатково можна вказати свій розмір в байтах і у разі помилки вивести повідомлення на екран

2022-11-02 13:40 UTC, YuraStork commented on src/utils/countBytes.ts
> +export const countBytes = (amount: number, type: 'MB' | 'KB') => {
Виправив

2022-11-02 17:49 UTC, Adm1RalDen commented on src/components/fileInput/styles.tsx
> +}
styled.div<{
  colorInfo: string | undefined
}>``

2022-11-02 17:53 UTC, Adm1RalDen commented on src/components/fileInput/types.ts
> +  colorInfo?: 'black' | 'white'
винеси в enum

2022-11-02 17:56 UTC, Adm1RalDen commented on src/components/image-crop/index.tsx
> +import { DataSizes } from 'const/enums'
DataSizes - не вичерпуюча назва, якщо ми хочемо перерахувати можливі розміри файлу, то обьективніше буде назвати типу FIleInputSizes

2022-11-02 18:00 UTC, Adm1RalDen commented on src/components/fileInput/index.tsx
> +      }
логічніше буде переревірити  if (isValidSize && isValidType), та не добавляли унарних операцій

2022-11-02 18:03 UTC, Adm1RalDen commented on src/components/fileInput/styles.tsx
> +const FileInputFileInfo = styled.div<Props>`
Можливо підійде FileInputInfoWrapper

2022-11-02 18:04 UTC, Adm1RalDen commented on src/components/fileInput/styles.tsx
> +  padding: 10px 10px 0px 0px;
продемонструй на маленьке відео будь ласка

2022-11-02 18:05 UTC, Adm1RalDen commented on src/components/fileInput/types.ts
> +  }
чи можливо використати interface замість type ?

2022-11-03 09:14 UTC, YuraStork commented on src/components/fileInput/styles.tsx
> +  padding: 10px 10px 0px 0px;
https://www.awesomescreenshot.com/video/12192591?key=34f11c00e17f8e5b4a985a56f873cef3

2022-11-03 11:45 UTC, YuraStork commented on src/components/fileInput/index.tsx
> +      }
Виправив

2022-11-03 11:45 UTC, YuraStork commented on src/components/image-crop/index.tsx
> +import { DataSizes } from 'const/enums'
Виправив

2022-11-03 11:45 UTC, YuraStork commented on src/components/fileInput/types.ts
> +  colorInfo?: 'black' | 'white'
Виніс

2022-11-03 11:45 UTC, YuraStork commented on src/components/fileInput/types.ts
> +  }
Використав

2022-11-03 11:46 UTC, YuraStork commented on src/components/fileInput/styles.tsx
> +const FileInputFileInfo = styled.div<Props>`
Виправив

2022-11-03 11:46 UTC, YuraStork commented on src/components/fileInput/styles.tsx
> +}
Виправив

2022-11-03 11:48 UTC, Andrew01011997 commented on src/utils/isValidFileSize.ts
> +        defaultSize ? defaultSize / 1024 / 1024 + 'MB' : '2MB'
Could you use function `countBytes` here?

2022-11-03 14:25 UTC, YuraStork commented on src/utils/isValidFileSize.ts
> +        defaultSize ? defaultSize / 1024 / 1024 + 'MB' : '2MB'
Ця функція не підходить так як вона генерує з МБ, КБ  - байти , а в даній ситуації потрібно перевести байти в мегабайти тому я створив нову функцію

2022-11-08 11:01 UTC, Andrew01011997 commented on src/utils/countMegaBytes.ts
> +export const countMegaBytes = (size: number) => size / 1024 / 1024
You already has this logic in countBytes function

2022-11-08 11:01 UTC, Andrew01011997 commented on src/utils/countBytes.ts
> +import { FIleInputSizes } from 'const/enums'
typo in naming

2022-11-08 11:12 UTC, YuraStork commented on src/utils/countMegaBytes.ts
> +export const countMegaBytes = (size: number) => size / 1024 / 1024
That function transform bytes to megabytes, prev function get MB or KB and transform to Bytes

2022-11-08 11:23 UTC, Adm1RalDen commented on src/utils/countBytes.ts
> +export const countBytes = (amount: number, type: keyof typeof FileInputSizes) => {
скоріше за все, має працювати й так `type: FileInputSizes`

2022-11-08 11:26 UTC, YuraStork commented on src/utils/countBytes.ts
> +export const countBytes = (amount: number, type: keyof typeof FileInputSizes) => {
Якщо у нас буде просто FileInputSizes, то ми зможемо передавати значення лише FileInputSizes.MB, а якщо keyof typeof FileInputSizes ми зможемо передавати значення **FileInputSizes.MB і 'MB'**

2022-11-08 11:27 UTC, Andrew01011997 approved these changes, later dismissed

2022-11-08 11:58 UTC, Andrew01011997 approved these changes

2022-11-08 11:59 UTC, merged