Dd 20 added reset password
Adm1RalDen/online-draw-dashboard pull request #39
Opened 2022-11-10 09:05 UTC by YuraStork

2022-11-10 10:16 UTC, Andrew01011997 requested changes

2022-11-10 10:16 UTC, Andrew01011997 commented on src/globals.d.ts
>  }
`declare module '*.svg' {`
 `   import * as React from 'react';`
``
    const ReactComponent: React.FunctionComponent<React.SVGProps<SVGSVGElement>>;
``
`    export default ReactComponent;`
`}`

Could you use this one?

2022-11-10 10:16 UTC, Andrew01011997 commented on src/hooks/useAppNavigate.tsx
> +}
could you return callback here and just call it when it needs?

2022-11-10 10:16 UTC, Andrew01011997 commented on src/hooks/useToastError.tsx
>  }
If you use this hook you should already know that this is error, probably you need to change this int `useToastMessage` and indicate what type of notification should be shown

2022-11-10 10:16 UTC, Andrew01011997 commented on src/pages/disableGoogleAuthentificator/index.tsx
> +  useAppNavigate(!isUse2FA, SETTINGS_URL)
does you meen useRedirect? this name will better understand what this hook does

2022-11-10 10:16 UTC, Andrew01011997 commented on src/pages/recoverPassword/content/index.tsx
> +      email: ''
why you add initial value for email?

2022-11-10 10:16 UTC, Andrew01011997 commented on src/pages/recoverPassword/content/index.tsx
> +      email: ''
could it be initial undefined?

2022-11-10 10:16 UTC, Andrew01011997 commented on src/pages/recoverPassword/index.tsx
> +    <Container>
could it be merged into 1 component?

2022-11-10 11:21 UTC, YuraStork commented on src/hooks/useAppNavigate.tsx
> +}
Потрібно будо створювати лишню перевірку

2022-11-11 12:11 UTC, Andrew01011997 approved these changes

2022-11-11 12:12 UTC, merged