Updated styles in home
Adm1RalDen/online-draw-dashboard pull request #4
Opened 2022-09-01 14:01 UTC by YuraStork

2022-09-05 13:21 UTC, Adm1RalDen commented on src/styles/typography/styles.tsx
> -  color: ${(p) => p.color || "#000"};
p.colors ?

2022-09-05 13:22 UTC, Adm1RalDen commented on src/pages/userCabinet/updateUserModal/index.tsx
> +          <Button type="submit">Save</Button>{" "}
Remove {" "}

2022-09-05 13:23 UTC, Adm1RalDen commented on src/pages/userCabinet/updateUserModal/index.tsx
> +import { Input } from "components/input/styles";
налаштуй дефолтний імпорт, щоб не було styles

2022-09-05 13:25 UTC, Adm1RalDen commented on src/pages/userCabinet/radioButtons/index.tsx
>            type={"color"}
через те що не налаштовано нормально prettier/linter - воно пропускає такий код, де ти використовуєш лишні фігурні дужки

2022-09-05 13:25 UTC, YuraStork commented on src/pages/userCabinet/updateUserModal/index.tsx
> +import { Input } from "components/input/styles";
Просто index?

2022-09-05 13:26 UTC, Adm1RalDen commented on src/pages/userCabinet/index.tsx
> +                <Button onClick={() => navigate(HOME_URL)}>Back</Button>
при кожному перемальовуванні цієї компоненти, дана функція буде пересторюватись лишні рази

2022-09-05 13:26 UTC, Adm1RalDen commented on src/pages/serverErrorPage/styles.tsx
>      font-size: 20px;
розмір шрифті та відступи необхідно винести в тему

2022-09-05 13:27 UTC, Adm1RalDen commented on src/pages/home/userRooms/card/update/index.tsx
> +            <Button onClick={() => setEditMode(false)}>cancel</Button>
дуже погана практика

2022-09-05 13:28 UTC, Adm1RalDen commented on src/pages/home/userRooms/card/update/index.tsx
>                checked={!!formik.values.isShow}
чи є у нас необхідність в !! ?

2022-09-05 13:30 UTC, Adm1RalDen commented on src/pages/home/createRoom/index.tsx
>        <h3>Create room</h3>
чому у нас немає стилізованих компонент для типографіки ?

2022-09-05 13:34 UTC, Adm1RalDen commented on src/components/form/styles.tsx
> +export const Form = styled.form``;
який сенс в цій компоненті ?

2022-09-05 13:35 UTC, Adm1RalDen requested changes
Потрібно вносити правки

2022-09-06 08:51 UTC, Adm1RalDen commented on src/components/image-crop/index.tsx
> +            <Button onClick={() => setEditMode(false)} type="button">
не всюди виніс лямбда функції

2022-09-06 08:51 UTC, Adm1RalDen commented on src/components/input-animation/index.tsx
> +      hasValue={!!rest.value}
які значення приходить в ці поля ?

2022-09-06 08:57 UTC, YuraStork commented on src/components/input-animation/index.tsx
> +      hasValue={!!rest.value}
string

2022-09-06 09:00 UTC, Adm1RalDen commented on src/components/input-animation/index.tsx
> +      {!!rest.error && <ErrorSpan title={rest.error}></ErrorSpan>}
<ErrorSpan title={rest.error}></ErrorSpan> - можна спросити  до <ErrorSpan title={rest.error} />, якщо rest.error у нас строка, нащо нам !! ?

2022-09-06 09:00 UTC, Adm1RalDen commented on src/components/input-animation/styles.tsx
> +    color: #888;
чому не використовуємо тему ?

2022-09-06 09:00 UTC, Adm1RalDen commented on src/components/settings/index.tsx
>          <input
чому не використовуємо компоненту input ?

2022-09-06 09:00 UTC, Adm1RalDen commented on src/components/toolbar/index.tsx
>            onChange={(e) => changeFillStyle(e.target.value)}
потрібно виносити функції

2022-09-06 09:00 UTC, Adm1RalDen commented on src/pages/auth/styles.tsx
> +const FormWrapper = styled.div``;
який в цьому сенс ?

2022-09-06 09:00 UTC, Adm1RalDen commented on src/pages/confirmAccessPage/index.tsx
>                  onChange={(e) => setPassword(e.target.value)}
так не можна залишати

2022-09-06 09:00 UTC, Adm1RalDen commented on src/pages/confirmAccessPage/index.tsx
> +              <ConfirmAccessPageButton onClick={() => navigate(HOME_URL)}>
виносити!

2022-09-06 13:00 UTC, Adm1RalDen approved these changes

2022-09-06 13:34 UTC, merged