DD-25: was created settings page
Adm1RalDen/online-draw-dashboard pull request #41
Opened 2022-11-14 15:46 UTC by YuraStork

2022-11-15 09:05 UTC, Andrew01011997 requested changes

2022-11-15 09:05 UTC, Andrew01011997 commented on src/components/logo/styles.tsx
> +  }
Should be `styled(LogoItem)`

2022-11-15 09:05 UTC, Andrew01011997 commented on src/components/search-input/index.tsx
> +) => <StyledSearchInput placeholder='Search here' {...props} type='text' />
`{...props}` should pe the last in props

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/components/header/index.tsx
> +  const handleChangeIsCollapsedSideBar = () => setIsCollapsedSideBar((prev) => !prev)
function's which changes state to opposite one should be named as `toggle...`

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/components/security/changePassword.tsx
> +      <ChangePasswordField />
Field can contain label inside to siplify usage

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/components/security/changePassword.tsx
> +      <Button disabled={true}>Update password</Button>
Why disabled true?

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/components/sidebar/index.tsx
> +        <SettingsPageSideBarLi isActive={false} onClick={handleLogOut}>
Why `isActive` is a hardcoded value?

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/components/sidebar/styles.tsx
> +export const SettingsPageSideBarLi = styled.li<{ isActive: boolean }>`
`SettingsPageSideBarLi` is bad naming. Tag shouldn't be as a part of component name

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/index.tsx
> +              <SettingsPageHeader setIsCollapsedSideBar={setIsCollapsedSideBar} />
`setIsCollapsedSideBar` is a bad property name. Create name which indicate what it doing inside component

2022-11-15 09:05 UTC, Andrew01011997 commented on src/pages/settings/styles.tsx
> +    grid-template-columns: ${(p) => (p.isCollapsedSideBar ? '0px' : '180px')} 1fr;
Could you try to use not static values as `px` and use `%`, `fr` and other dynamic values?

2022-11-15 09:05 UTC, Andrew01011997 commented on src/styles/themes.tsx
> +    mobile: '450px'
Why you change colors and break point?

2022-11-15 09:05 UTC, Andrew01011997 commented on src/styles/typography/styles.tsx
> +  color: ${(p) => (p.color ? p.color : 'inherit')};
`p.color ?? 'inherit` will be better. IMHO

2022-11-15 09:18 UTC, Adm1RalDen commented on src/components/label/index.tsx
> +  font-size: 15px;
двічі прописано font-size, при чому, перший раз ми дістаємо з теми, що правильно, а другий руками - що заборонено

2022-11-15 09:20 UTC, Adm1RalDen commented on src/components/search-input/styles.tsx
> +    font-size: 14px;
використовуй theme для font-size  та приведи до одного стандарту розміри шрифті, яка різниця що ти десь прописуєш 14 чи 15 пікселів ?

2022-11-15 09:21 UTC, Adm1RalDen commented on src/pages/settings/components/header/index.tsx
> +}
навіщо ти добавив стільки відступів поміж імпортами файлів ?

2022-11-15 09:23 UTC, Adm1RalDen commented on src/pages/settings/components/header/index.tsx
> +      <UserIcon src={setImageUrl(avatar)} />
setImageUrl - не схоже що ця функція має щось повертати, якщо вона повертає сформаване посилання на урлу користувача, то має бути названа відповідно

2022-11-15 09:26 UTC, Adm1RalDen commented on src/pages/settings/components/security/changePassword.tsx
> +      <Button disabled={true}>Update password</Button>
disabled={true}  може бути спрощено до  disabled

2022-11-15 09:28 UTC, Adm1RalDen commented on src/pages/settings/components/security/changeTwoFa.tsx
> +        </div>
ці для блока ідентичні по своїй структурі, є сенс винести це в окрему підкомпоненту та передати туди потрібні аргументи

2022-11-15 09:29 UTC, Adm1RalDen commented on src/pages/settings/components/security/index.tsx
> +)
ця компонента не виглядає потрібною, на скільки багато разів ти перевикористовуєш її ?

2022-11-15 09:32 UTC, Adm1RalDen commented on src/pages/settings/components/sidebar/index.tsx
> +          <ArrowLeftOnRectangleIcon /> <span>Log Out</span>
вінформатуй код, чому в одній стрічці в тебе дві компоненти прописані

2022-11-15 09:32 UTC, Adm1RalDen commented on src/pages/settings/components/sidebar/styles.tsx
> +  font-size: 16px;
використовуй тему!

2022-11-15 09:33 UTC, Adm1RalDen commented on src/pages/settings/components/sidebar/styles.tsx
> +  padding: 10px 10px 10px 10px;
в тебе все добре ?

2022-11-15 09:34 UTC, Adm1RalDen commented on src/pages/settings/components/sidebar/styles.tsx
> +    z-index: 2;
використуй заголовлені з тами значення

2022-11-15 09:34 UTC, Adm1RalDen commented on src/pages/settings/components/sidebar/styles.tsx
> +    z-index: 1;
використуй заголовлені з тами значення

2022-11-15 09:37 UTC, Adm1RalDen commented on src/pages/settings/styles.tsx
> +    grid-template-columns: ${(p) => (p.isCollapsedSideBar ? '0px' : '180px')} 1fr;
Можливо  `@media screen and (max-width: ${({ theme }) => theme.breakPoints.tablet})` - це можна скоротити, якщо винести  screen and (max-width: ...) як значення теми
<img width="649" alt="image" src="https://user-images.githubusercontent.com/33317394/201884663-d3878039-1fe1-4f7a-b648-e5e866b4c208.png">

2022-11-15 09:39 UTC, Adm1RalDen commented on src/pages/settings/styles.tsx
> +  padding: 10px 20px;
так як у нас немає дизайнера, і ми можемо самі задавати відступи, було б чудово прийти до одного стилю відступів, у нас немає причин всю робити відступи різниз розмірів, визначись з відступами для елементів для різних типів пристроїв, та запиши ці значення  в тему, відповідно перевикористай їх по всьому проекту

2022-11-15 09:43 UTC, Adm1RalDen commented on src/styles/themes.tsx
> +    mobile: '450px'
використовуй [популярні значення](https://polypane.app/blog/the-breakpoints-we-tested-in-2021-and-the-ones-to-test-in-2022/), припини вигадувати велосипеди!

2022-11-15 12:26 UTC, YuraStork commented on src/pages/settings/components/sidebar/index.tsx
> +        <SettingsPageSideBarLi isActive={false} onClick={handleLogOut}>
Because its li with logout action

2022-11-15 12:40 UTC, YuraStork commented on src/pages/settings/components/security/index.tsx
> +)
рівно на 1, вона потрібна томущо вона являється категорією налаштувань - **security**

2022-11-15 12:44 UTC, YuraStork commented on src/pages/settings/components/header/index.tsx
> +}
Це не я, це eslint+prettier

2022-11-16 13:13 UTC, Andrew01011997 requested changes

2022-11-16 13:13 UTC, Andrew01011997 commented on src/components/field/index.tsx
> +export const Field: FC<FieldProps> = ({ showError = true, label, ...props }) => {
Create more specific name

2022-11-16 13:13 UTC, Andrew01011997 commented on src/pages/home/chat/message/index.tsx
> +      src={getImageUrl(`users/${msg.userId}/${msg.userId}_avatar.png`)}
destruct `msg` upper and use as simple variables

2022-11-16 13:13 UTC, Andrew01011997 commented on src/pages/settings/components/header/index.tsx
> +  const handleToggleMobileAside = () => toggleMobileAside((prev) => !prev)
Wrong function name changed

2022-11-16 13:13 UTC, Andrew01011997 commented on src/pages/settings/components/security/changePassword.tsx
> +    onSubmit: (data) => console.log(data)
No console in project

2022-11-16 13:13 UTC, Andrew01011997 commented on src/pages/settings/components/security/changeTwoFa.tsx
> +  const { isUse2FA } = useAppSelector(userDataSelector)
Create new selector to avoid data destruction. If data will changed selector will update value, if you destruct it here it also updates each time when `userData` changed

2022-11-16 13:13 UTC, Andrew01011997 commented on src/pages/settings/components/security/changeTwoFa.tsx
> +              Two factor authentication is enabled yet. <br /> You can disable it.
Should it be `Two factor authentication has been already enabled`?

2022-11-16 13:13 UTC, Andrew01011997 commented on src/pages/settings/components/sidebar/styles.tsx
> +  padding: ${({ theme }) => theme.spacing.s} 0px;
`0` is always `0`, `px` is redunant here

2022-11-16 13:13 UTC, Andrew01011997 commented on src/styles/themes.tsx
> +const colors = {
divide this file into separate files to have config only for one part per file

2022-11-16 13:13 UTC, Andrew01011997 commented on src/types.ts
> +export type ChangeStateAction<T> = React.Dispatch<React.SetStateAction<T>>
Do you really need this change?

2022-11-16 13:26 UTC, YuraStork commented on src/types.ts
> +export type ChangeStateAction<T> = React.Dispatch<React.SetStateAction<T>>
Yes i need it

2022-11-18 13:55 UTC, Andrew01011997 requested changes

2022-11-18 13:55 UTC, Andrew01011997 commented on src/pages/home/chat/index.tsx
> +            <ChatMessage key={msg._id} msg={msg} id={data.id} onError={onError} />
```suggestion
            <ChatMessage key={msg._id} msg={msg} currentUserId={data.id} onError={onError} />
```

2022-11-18 14:05 UTC, Andrew01011997 approved these changes

2022-11-18 14:05 UTC, merged