Dd 27 Added Fields and fixed bag with twoFa
Adm1RalDen/online-draw-dashboard pull request #45
Opened 2022-12-05 13:52 UTC by YuraStork

2022-12-12 11:11 UTC, Andrew01011997 requested changes

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/disableGoogleAuthentificator/index.tsx
> +          {isSuccess || !isUse2FA ? (
can you just update `isUse2FA` value for remove `isSuccess` from here?

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/disableGoogleAuthentificator/index.tsx
> +            </FormikProvider>
Create a separate component for this logic, this also help to use `formik` value only if it needs

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/enableGoogleAuthentificator/index.tsx
> +        {isUse2FA && currentStep < 5 ? (
what means `5`? Could you create a descriptive constant to understand what is this step?

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/enableGoogleAuthentificator/index.tsx
> +            <AuthentificatorStepsPanel currentStep={currentStep} />
Does this progress bar?

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/enableGoogleAuthentificator/steps/enable/index.tsx
> +  }, [sendLetter, hasLetterSent])
Letter shouldn't sent to user when he comes into this route. You should add a confirmation for sending (to fix problems with reloading page)

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/enableGoogleAuthentificator/steps/enable/index.tsx
> +        <form onSubmit={formik.handleSubmit}>
Can you use `Form` with `formik`? It has onSubmit logic inside, so you don't need to pass `formik.handleSubmit' inside manually

2022-12-12 11:11 UTC, Andrew01011997 commented on src/pages/enableGoogleAuthentificator/steps/enable/index.tsx
> +          <InputField
`Field` means you don't need to set `value` and `onChamge` manually (here `type` also), you just need to pass `name` for work with this field element

2022-12-12 14:01 UTC, YuraStork commented on src/pages/enableGoogleAuthentificator/index.tsx
> +            <AuthentificatorStepsPanel currentStep={currentStep} />
yes it does

2022-12-12 14:10 UTC, YuraStork commented on src/pages/enableGoogleAuthentificator/steps/enable/index.tsx
> +          <InputField
In current situation i need pass onChange callback because this callback has a logic to input text (only 6 numbers)

2022-12-12 15:31 UTC, YuraStork commented on src/pages/disableGoogleAuthentificator/index.tsx
> +            </FormikProvider>
I think its a bad idia because in us can be different input by types and this component will not offten use. I only created other component for form

2022-12-15 14:02 UTC, Andrew01011997 approved these changes, later dismissed

2022-12-15 14:06 UTC, Andrew01011997 approved these changes

2022-12-15 14:07 UTC, merged