DD-32 fixed types
Adm1RalDen/online-draw-dashboard pull request #46
Opened 2022-12-05 14:35 UTC by YuraStork

2022-12-09 13:03 UTC, Andrew01011997 requested changes

2022-12-09 13:03 UTC, Andrew01011997 commented on src/hooks/useCanvas/const.ts
>      default:
Can be converted to object

2022-12-09 13:03 UTC, Andrew01011997 commented on src/hooks/useCanvas/methods/setDrawConnection.ts
> +          Pen.drawOnline({ ctx, ...(data as SocketDrawResponse) } as DrawPenParams)
Same comment as above (to object)

2022-12-09 13:03 UTC, Andrew01011997 commented on src/hooks/useCanvas/types.ts
> +  navigate: NavigateFunction
Why navigate passed as prop?

2022-12-09 13:03 UTC, Andrew01011997 commented on src/types/canvas.ts
> +  b: number
What means `a`, `b`?

2022-12-09 13:03 UTC, Andrew01011997 commented on src/types/canvas.ts
> +  b: number
For draw circle you need only `x`, `y` position and `radius`

2022-12-09 13:03 UTC, Andrew01011997 commented on src/types/canvas.ts
> +  y1: number
You don't need size of eraser do know how much should be cleared?

2022-12-09 13:03 UTC, Andrew01011997 commented on src/types/canvas.ts
> +  | (Omit<DrawSquareParams, 'ctx'> & { tool: DrawTools.SQUARE })
Create local type which removes `ctx` from each item and add tool property

2022-12-09 13:03 UTC, Andrew01011997 commented on src/types/canvas.ts
> +}
I prefer `extends` from interfaces for this types of extending

2022-12-09 13:16 UTC, YuraStork commented on src/hooks/useCanvas/types.ts
> +  navigate: NavigateFunction
Because inside function **setConnection** will use navigate for some socket listeners

2022-12-09 13:24 UTC, YuraStork commented on src/types/canvas.ts
> +  b: number
From this values will extract a radius

2022-12-09 13:24 UTC, YuraStork commented on src/types/canvas.ts
> +  y1: number
For now without size

2022-12-09 13:34 UTC, YuraStork commented on src/types/canvas.ts
> +}
I also but "An interface can only extend an object type or intersection of object types with statically known members"

2022-12-09 14:04 UTC, YuraStork commented on src/hooks/useCanvas/methods/setDrawConnection.ts
> +          Pen.drawOnline({ ctx, ...(data as SocketDrawResponse) } as DrawPenParams)
Here only switch because typescript doesn`t like object

2022-12-12 09:14 UTC, Andrew01011997 requested changes

2022-12-12 09:14 UTC, Andrew01011997 commented on src/hooks/useCanvas/const.ts
> +    [DrawTools.LINE]: () => new Line(canvasRef, socket, roomId)
leave here only class and use `new` after tool will selected from object. After this change you can move object out of function

2022-12-12 09:14 UTC, Andrew01011997 commented on src/hooks/useCanvas/methods/setDrawConnection.ts
> +          Pen.drawOnline({ ctx, ...(data as SocketDrawResponse) } as DrawPenParams)
I don't see any restrictions here to convert it to object like `{ [DrawTools.Circle]: Circle.drawOnline }`

2022-12-15 13:48 UTC, Andrew01011997 approved these changes

2022-12-15 14:05 UTC, merged