DD-12 took out the functions from const and formatted
Adm1RalDen/online-draw-dashboard pull request #47
Opened 2022-12-05 15:10 UTC by YuraStork

2022-12-05 16:00 UTC, Andrew01011997 requested changes

2022-12-05 16:00 UTC, Andrew01011997 commented on src/api/utils.ts
> +})
Це всі можливі хедерси які будуть в проекті?
Коли відправляти потрібно файли в хедерсах має бути content-type, чому його тут нема?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/api/utils.ts
> +})
Не зрозуміло куди і навіщо сетається refreshToken? Чому ця функція повертає обʼєкт також не зрозуміло

2022-12-05 16:00 UTC, Andrew01011997 commented on src/hooks/useCanvas/index.tsx
> +/* eslint-disable @typescript-eslint/no-non-null-assertion*/
Видалити, не використовуй дісейбли якщо це не потрібно

2022-12-05 16:00 UTC, Andrew01011997 commented on src/hooks/useCanvas/index.tsx
> +  const canvasRef = useRef<HTMLCanvasElement>(null!)
null! - брєд

2022-12-05 16:00 UTC, Andrew01011997 commented on src/hooks/useCanvas/index.tsx
>      /* eslint-disable-next-line react-hooks/exhaustive-deps*/
Якщо це буде ще десь в проекті вимикатися, то можна взагалі прибрати це правило

2022-12-05 16:00 UTC, Andrew01011997 commented on src/hooks/useCanvas/index.tsx
>        canvasRef.current.width = setCanvasWidth()
Забагато логіки в 1 хук. Можна розділити на декілька хуків. Багато чого передаватися має аргументами

2022-12-05 16:00 UTC, Andrew01011997 commented on src/hooks/useCanvas/methods/setDrawConnection.ts
> +export const setDrawConnection = (data: DrawConnectionProps) => {
Якщо дата більше ніде не використовується то можна деструктуризувати відразу в цій лінії

2022-12-05 16:00 UTC, Andrew01011997 commented on src/hooks/useCanvas/methods/setDrawConnection.ts
>    socket.on(SEND_SNAPSHOT_SOCKET, (ownerId, recipient) => {
чому не створити сокет сервіси, які б повертали обʼєкт сокета, передаючи їм назву сокета? екшени для сокету також можна інкапсулювати в сервісі

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/confirmAccessPage/index.tsx
> +  const [roomPassword, setPassword] = useState('')
Чи є сенс на кожен введений символ перерендерювати компонент?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/confirmAccessPage/utils.ts
> +  const { socket, navigate, setIsLoading } = data
аналогічно до попереднього коментаря про деструктуризацію

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/createRoom/index.tsx
> +  const { id, name } = useAppSelector(userDataSelector)
створити окремі селектори для id та name, якщо там не тільк. ці 2 поля

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/createRoom/utils.ts
> +  setIsLoading(true)
Передавати лишній раз колбеки - погана практика

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/enterInRoom/index.tsx
>    const { socket } = useSocket()
Цей сокет більш ніде не використовується, він точно потрібен?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/index.tsx
>    const [userRooms, setUserRooms] = useState<ActiveRoom[]>([])
Де використовується `userRooms`?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/userRooms/card/update/index.tsx
> +    onSubmit: (data) => handleUpdate({ data, socket, room, userId, setIsLoading, setEditMode })
`setIsLoading`, `setEditMode` не потрібно ці колбеки передавати в іншу функцію

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/userRooms/card/update/utils.ts
> +  const { room, userId, data, socket, setIsLoading, setEditMode } = params
з `room` тобі потірбьна тільки `id`, навіщо передавати весь обʼєкт `room`?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/userRooms/card/update/utils.ts
> +  const keys = Object.keys(data) as (keyof HandleUpdateParams['data'])[]
Тут можна типізувати без `as`

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/userRooms/card/update/utils.ts
> +    .reduce((acum: any, key: keyof HandleUpdateParams['data']) => {
`acum` не має бути `any`

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/userRooms/card/update/utils.ts
> +    .reduce((acum: any, key: keyof HandleUpdateParams['data']) => {
`key` і так такого типу, його не потрібно додатково типізувати

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/home/utils.ts
> +const accessPermitted: AccessPermittedParams = (id, navigate, setIsLoading) => {
`setIsLoading` не має бути тут

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/layout/index.tsx
>      <PaintContext.Provider value={{ ...data }}>
навіщо деструктуризувати щоб потім структуризувати назад?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/onlineDrawPage/index.tsx
>    const [access, setAccess] = useState(false)
навіщо? В тебе є state який ти перевіряєш, чому просто його не використати для перевірки?

2022-12-05 16:00 UTC, Andrew01011997 commented on src/pages/onlineDrawPage/utils.ts
> +  const { navigate, setIsLoading, setAccess, roomId, userId, socket } = data
прибрати колбеки

2022-12-06 09:00 UTC, YuraStork commented on src/api/utils.ts
> +})
When we send files we use FormData, and by default browser set header **Content-type: 'multipart/form-data'**

2022-12-06 09:46 UTC, YuraStork commented on src/pages/home/index.tsx
>    const [userRooms, setUserRooms] = useState<ActiveRoom[]>([])
```
   <UserRooms
            userRooms={userRooms}
            userId={id}
            userName={name}
            isLoading={isLoading}
            setIsLoading={setIsLoading}
          />
```

2022-12-06 09:57 UTC, YuraStork commented on src/pages/home/userRooms/card/update/utils.ts
> +  const { room, userId, data, socket, setIsLoading, setEditMode } = params
```
  const res = keys
    .filter((key) => data[key] !== room[key])
    .reduce((acum: any, key) => {
      acum[key] = data[key]
      return acum
    }, {})
```

2022-12-06 10:30 UTC, YuraStork commented on src/pages/onlineDrawPage/utils.ts
> +  const { navigate, setIsLoading, setAccess, roomId, userId, socket } = data
Залишив лише navigate для навігації

2022-12-06 11:18 UTC, YuraStork commented on src/hooks/useCanvas/index.tsx
> +/* eslint-disable @typescript-eslint/no-non-null-assertion*/
Виніс в DD-34

2022-12-06 11:18 UTC, YuraStork commented on src/hooks/useCanvas/index.tsx
> +  const canvasRef = useRef<HTMLCanvasElement>(null!)
Виніс в DD-34

2022-12-06 11:18 UTC, YuraStork commented on src/hooks/useCanvas/index.tsx
>        canvasRef.current.width = setCanvasWidth()
Виніс в DD-34

2022-12-06 11:18 UTC, YuraStork commented on src/hooks/useCanvas/methods/setDrawConnection.ts
>    socket.on(SEND_SNAPSHOT_SOCKET, (ownerId, recipient) => {
Виніс в DD-34

2022-12-06 14:25 UTC, Andrew01011997 approved these changes

2022-12-15 14:04 UTC, merged